ARM:
  JOINT_NAMES: [
  'panda_joint1',
  'panda_joint2',
  'panda_joint3',
  'panda_joint4',
  'panda_joint5',
  'panda_joint6',
  'panda_joint7',
  ]

GRIPPER:
  L_FINGER_NAME: "panda_finger_joint1"
  R_FINGER_NAME: "panda_finger_joint2"
  L_FINGER_TIP_NAME: "panda_leftfinger"
  R_FINGER_TIP_NAME: "panda_rightfinger"

EE_NAME: "panda_hand"


NEUTRAL_JOINT_POSITIONS: [
  0.,
  0.458,
  0.31,
  -2.24,
  -0.30,
  2.66,
  2.32,
]

URDF_NAME: "robots/panda/panda.urdf"
ASSETS_DIR: "default"
